### ISSUE TITLE
1주차 - JVM 구조와 컴파일 동작방식 

### ISSUE THREAD

**Issue by ajongs** [ajongs/JAVA_STUDY#1]
## 주제
- JVM이란 무엇인가
- 컴파일 하는 방법
- 실행하는 방법
- 바이트코드란 무엇인가
- JIT 컴파일러란 무엇이며 어떻게 동작하는지
- JVM 구성 요소
- JDK와 JRE의 차이

**Comment by CRITICBANGGU** [comment]
https://velog.io/@criticbanggu/JAVA-%EC%8A%A4%ED%84%B0%EB%94%94-1%EC%A3%BC%EC%B0%A8

**Comment by seoyeon0219** [comment]
https://velog.io/@bssssyyi/JAVA-STUDY1%EC%A3%BC%EC%B0%A8

**Comment by bibimh** [comment]
https://feather-chokeberry-4b8.notion.site/Chapter-01-a6d2710bb7e04939abeaa9f5eb47f08b

**Comment by ajongs** [comment]
https://velog.io/@ajongs/JVM-%EA%B5%AC%EC%A1%B0%EC%99%80-%EC%BB%B4%ED%8C%8C%EC%9D%BC-%EB%B0%A9%EC%8B%9D
