### ISSUE TITLE
2주차 - 프리미티브 타입, 변수, 배열

### ISSUE THREAD

**Issue by ajongs** [ajongs/JAVA_STUDY#2]
## 과제
- 프리미티브 타입 종류와 값의 범위 그리고 기본 값
- 프리미티브 타입과 레퍼런스 타입
- 리터럴
- 변수 선언 및 초기화하는 방법
- 변수의 스코프와 라이프타임
- 타입 변환, 캐스팅 그리고 타입 프로모션
- 1차 및 2차 배열 선언하기
- 타입 추론, var

**Comment by seoyeon0219** [comment]
https://velog.io/@bssssyyi/JAVA-%EC%8A%A4%ED%84%B0%EB%94%942

**Comment by ajongs** [comment]
https://velog.io/@ajongs/JAVA-%ED%94%84%EB%A6%AC%EB%AF%B8%EB%B9%84%ED%8A%B8-%ED%83%80%EC%9E%85-%EB%B3%80%EC%88%98-%EB%B0%B0%EC%97%B4

**Comment by bibimh** [comment]
https://feather-chokeberry-4b8.notion.site/Chapter-02-b58d1b043b8c40318447b04a0ccd33c4

**Comment by CRITICBANGGU** [comment]
https://velog.io/@criticbanggu/JAVA-%EC%8A%A4%ED%84%B0%EB%94%94-2%EC%A3%BC%EC%B0%A8
