### ISSUE TITLE
3주차 - 클래스와 객체

### ISSUE THREAD

**Issue by ajongs** [ajongs/JAVA_STUDY#3]
# 과제
- 클래스를 정의하는 방법
- 객체 만드는 방법
- 메소드 정의하는 방법
- 생성자 정의하는 방법
- this 키워드 이해하기

### LinkedList 구현
- 정수 저장하는 ListNode 클래스 구현
- ListNode add(ListNode head, ListNode nodeToAdd, int position) 구현
- ListNode remove(ListNode head, int positionToRemove) 구현
- boolean contains(ListNode head, ListNode nodeToCheck) 구현

### Stack 구현
- int 배열을 사용해서 정수를 저정하는 Stack 구현
- void push(int data) 구현
- int pop() 구현

### ListNode를 사용해서 Stack을 구현
- ListNode head를 가지고 있는 ListNodeStack 클래스를 구현하세요
- void push(int data) 구현
- int pop() 구현

### Queue 구현
- 배열을 사용해서 한번
- ListNode를 사용해서 한번

**Comment by ajongs** [comment]
LinkedList 구현할때는 양방향이 아니라 단방향으로 구현해봐 
자바에서 구현되어 있는 LinkedList는 양방향인데 아직 양방향을 하기에는 고려해야될 것도 많고 어려움이 많을 것 같으니까 단방향으로 하도록!

**Comment by ajongs** [comment]
과제 내용이 조금 버거운 친구들은 클래스와 객체 관련 과제는 꼭하고 자료구조 과제는 할 수 있는데 까지만 해와

**Comment by seoyeon0219** [comment]
https://velog.io/@bssssyyi

**Comment by bibimh** [comment]
https://feather-chokeberry-4b8.notion.site/Chapter-03-268090d7b42c405d9f874f645509b8bf
