### ISSUE TITLE
4주차 - 인터페이스와 상속

### ISSUE THREAD

**Issue by ajongs** [ajongs/JAVA_STUDY#4]
# 과제
## 상속
- 자바 상속의 특징
- super 키워드
- 메소드 오버라이딩
- 다이나믹 메소드 디스패치
- 추상 클래스
- final 클래스
- object 클래스

## 인터페이스
- 인터페이스 정의하는 방법
- 인터페이스 구현하는 방법
- 인터페이스 레퍼런스를 통해 구현체를 사용하는 방법
- 인터페이스 상속
- 인터페이스의 기본 메소드 (Default Method), 자바 8 이상
- 인터페이스의 static 메소드, 자바8
- 인터페이스의 private 메소드, 자바9

**Comment by seoyeon0219** [comment]
https://velog.io/@bssssyyi/JAVA-%EC%8A%A4%ED%84%B0%EB%94%944-u2al1mjs

**Comment by CRITICBANGGU** [comment]
-상속
https://velog.io/@criticbanggu/JAVA-%EC%8A%A4%ED%84%B0%EB%94%94-4%EC%A3%BC%EC%B0%A8-%EC%83%81%EC%86%8D

-인터페이스
https://velog.io/@criticbanggu/JAVA-%EC%8A%A4%ED%84%B0%EB%94%94-5%EC%A3%BC%EC%B0%A8-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4

**Comment by bibimh** [comment]
상속
https://feather-chokeberry-4b8.notion.site/Chapter-04-8f47e2d04fcb4632b21ef809ecd55d5b

인터페이스
https://feather-chokeberry-4b8.notion.site/Chapter-05-26b9c8f967f44fa183c8744ef8439d0d
