### ISSUE TITLE
5주차 - 패키지와 Collection Framework

### ISSUE THREAD

**Issue by ajongs** [ajongs/JAVA_STUDY#5]
# 과제
## 패키지
- package 키워드
- import 키워드
- 클래스패스
- CLASSPATH 환경변수
- -classpath 옵션
- 접근지시자
## 컬렉션
- 자바 컬렉션 종류와 상속도
- 각 컬렉션의 특징과 사용법

**Comment by CRITICBANGGU** [comment]
https://velog.io/@criticbanggu/JAVA-%EC%8A%A4%ED%84%B0%EB%94%94-6%EC%A3%BC%EC%B0%A8-package-%ED%81%B4%EB%9E%98%EC%8A%A4%ED%8C%A8%EC%8A%A4

**Comment by seoyeon0219** [comment]
https://velog.io/@bssssyyi/JAVA-%EC%8A%A4%ED%84%B0%EB%94%945

**Comment by ajongs** [comment]
> https://velog.io/@criticbanggu/JAVA-%EC%8A%A4%ED%84%B0%EB%94%94-6%EC%A3%BC%EC%B0%A8-package-%ED%81%B4%EB%9E%98%EC%8A%A4%ED%8C%A8%EC%8A%A4

@CRITICBANGGU package 쪽은 평소보다 열심히 한 것 같은데 컬렉션 구조만 파악한게 좀 아쉽네. 그 안에 인터페이스와 클래스들까지 상세하게 알아보았으면 좋았을 것 같은데. 각 컬렉션 인터페이스에서 제공하는 API(메소드)들이랑 컬렉션 인터페이스를 구현한 구현체 클래스(ex. ArrayList, LinkedList, HashMap, TreeMap)의 특징과 메소드들에 대해서 좀더 깊게 공부해봐. 이 부분이 객체 지향적으로 아주 잘짜여 있어서 인텔리제이로 소스코드 확인하면서 공부하면 인터페이스랑 상속에 대해서 좀 더 이해가 갈 듯!

**Comment by ajongs** [comment]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/35219960/182291151-8b28ea4e-4fde-4187-8fd8-6d1706e8198f.png">

컬렉션 상속구조는 이게 젤 정확한 것 같아보이네
여기서 Map은 빠져 있어

**Comment by bibimh** [comment]
https://feather-chokeberry-4b8.notion.site/Chapter-06-26b9c8f967f44fa183c8744ef8439d0d
