### ISSUE TITLE
6주차 - 예외, Hash

### ISSUE THREAD

**Issue by ajongs** [ajongs/JAVA_STUDY#6]
### 예외
- 자바에서 예외처리 방법 (try, catch, throw, throws, finally)
- 자바가 제공하는 예외 계층 구조
- Exception과 Error의 차이?
- RuntimeException과 그냥 Exception과의 차이
- 커스텀한 예외 만드는 방법
- Exception클래스 getMessage() 사용 방법 : 소스코드 구현
- 멀티캐치 (소스코드 구현) : 커스텀한 예외 클래스인 ExceptionA와 ExceptionB 먼저 구현, 이때 ExceptionA클래스에 
   public void printMethod(){ System.out.println("ExceptionA의 printMethod() 호출!!"); } 
   메서드를 꼭 작성하고,
  ExceptionA와 ExceptionB를 멀티캐치문에서 ExceptionA의 메소드 printMethod()를 호출하도록 예외를 처리하시오.
- try-with-resources 도입된 배경과 사용법

### Hash
- Hash
- HashTable
- Hash함수
- hashCode()
- HashMap의 동작원리

**Comment by CRITICBANGGU** [comment]
예외처리

https://velog.io/@criticbanggu/Java-%EC%8A%A4%ED%84%B0%ED%8B%B0-7%EC%A3%BC%EC%B0%A8-%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC

Hash
https://velog.io/@criticbanggu/Java-%EC%8A%A4%ED%84%B0%EB%94%94-7%EC%A3%BC%EC%B0%A8-Hash

**Comment by seoyeon0219** [comment]
https://velog.io/@bssssyyi/JAVA-%EC%8A%A4%ED%84%B0%EB%94%946

**Comment by bibimh** [comment]
https://feather-chokeberry-4b8.notion.site/Chapter-07-46124a4325034faf8625f91d973163bb
